spring:
  application:
    name: sample-app-spring-graphql
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    hikari:
      connection-timeout: 2000
      initialization-fail-timeout: 0
  h2:
    console:
      enabled: true
      path: /h2-console
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true

server:
  port: 8082

  # application.yml
  mybatis:
    configuration:
      map-underscore-to-camel-case: true
      default-fetch-size: 100
      default-statement-timeout: 30